name: myWorkflowTeste

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    #"standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2
      
    #Using another action for AsyncAPI for validation
#     - name: Validating AsyncAPI document
#       uses: WaleedAshraf/asyncapi-github-action@v0
#       with:
#         filepath: docs/api/my-asyncapi.yml

    # Generate
    - name: Generating Markdown from my AsyncAPI document
      uses: asyncapi/github-action-for-generator@v1
    
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: SECRET_VALUE
        BRANCH: main
        FOLDER: generated-html
    
    - name: teste
      run: ls -la
