name: myWorkflowTeste

env:
  ymlFilepath: docs/api/my-asyncapi.yml
  generatedPath: output/generated
  SUPER_SECRET: ${{ secrets.SECRET_NAME }}

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    # "standard step" where repo needs to be checked-out first
    - name: Checkout repo
      uses: actions/checkout@v2

    #Using another action for AsyncAPI for validation
    #- name: Validating AsyncAPI document
    #  uses: WaleedAshraf/asyncapi-github-action@v1
    #  with:
    #    filepath: ${{ env.ymlFilepath }}

    - name: Generating HTML from my AsyncAPI document
      uses: asyncapi/github-action-for-generator@v1
      with:
        template: '@asyncapi/html-template@0.15.4'  #In case of template from npm, because of @ it must be in quotes
        filepath: ${{ env.ymlFilepath }}
        parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
        output: ${{ generatedPath }}
        
    #Using another action that takes generated HTML and pushes it to GH Pages
    - name: Deploy GH page
      uses: JamesIves/github-pages-deploy-action@3.4.2
      with:
        ACCESS_TOKEN: ${{ env.SUPER_SECRET }}
        BRANCH: main
        FOLDER: .